- hosts: all
  gather_facts: no

  tasks:
    - name: special task
      shell: echo 'yeah!'
      register: result
      # BEGIN (write your solution here)
      tags: special
      # END

    - name: 'Check tags'
      fail: msg='Expected result is defined'
      when: result is not defined
      tags: special

